- name: install main desktop packages with pacman
  community.general.pacman:
    name: "{{ base_packages.pacman + hypr_ecosystem.pacman + terminal_packages.pacman }}"
    state: present
  become: true

- name: install main desktop packages with "{{ options.aur_helper.name }}"
  kewlfft.aur.aur:
    name: "{{ base_packages.aur + hypr_ecosystem.aur + terminal_packages.aur }}"
    use: "{{ options.aur_helper.name }}"
    state: present
  become: true
  become_user: aur_builder
