---
  
- name: Install gpu utils
  community.general.pacman:
    name: "{{ amdgpu_packages }}"
    state: present
  become: true

- name: Install lact with paru
  kewlfft.aur.aur:
    use: "{{ options.aur_helper.name }}"
    name: lact
    state: present
  become: true
  become_user: aur_builder
   
- name: Enable lact
  ansible.builtin.systemd_service:
    name: lactd
    enabled: yes
  become: true
