---
  
- name: Install gpu utils.
  community.general.pacman:
    name: "{{ amdgpu_packages }}"
    state: present
   
- name: Enable lactd service.
  ansible.builtin.systemd:
    name: lactd
    enabled: true
