---

- name: Install ufw.
  community.general.pacman:
    name: ufw
    state: present

- name: Disable IPv6.
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true  
  loop:
    - { key: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { key: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
    - { key: 'net.ipv6.conf.lo.disable_ipv6', value: '1' }

- name: Disable ipv6 rule in ufw.
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^IPV6=yes'
    line: IPV6=no

- name: Allow ports (tcp).
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ firewall.allow_ports }}"

- name: Allow ports (udp).
  community.general.ufw:
    rule: allow
    port: "{{ firewall.allow_ports[-1] }}"
    proto: udp

- name: Deny ports.
  community.general.ufw:
    rule: deny
    port: "{{ firewall.deny_port }}"
    proto: tcp

- name: Set ufw default policy to deny incomming.
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set ufw default policy to allow outgoing trafic.
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Enable ufw.
  community.general.ufw:
    state: enabled
