---

-  name: Archlinux post-installation - System
   hosts: host
   connection: local
   gather_facts: false
   become: true
   vars_files:
     - ../group_vars/all/vars.yml
     - ../group_vars/all/options.yml
   tasks:

     - name: Copy pacman.conf.
       ansible.builtin.copy:
         src: pacman.conf
         dest: /etc/pacman.conf
         owner: root
         group: root
         mode: 0644
       register: pacman_config

     - name: Reload pacman.
       community.general.pacman:
         update_cache: true
       when: pacman_config.changed

     - name: Copy makepkg config file.
       ansible.builtin.copy:
         src: makepkg.conf
         dest: /etc/makepkg.conf
         owner: root
         group: root
         mode: 0644

     - name: Install "{{ options.aur_helper.name }}" (aur).
       kewlfft.aur.aur:
         name: "{{ options.aur_helper.name + '-git' if options.aur_helper.git else options.aur_helper.name + '-bin' }}"
         use: makepkg
         state: present
       become_user: "{{ user.name }}"
  
     - name: Install ly.
       ansible.builtin.pacman: 
         name: ly
         state: present

     - name: Enable ly service.
       ansible.builtin.systemd_service:
         name: ly
         enabled: yes

     - ansible.builtin.import_tasks: amdgpu.yml
       when: options.amdgpu

     - ansible.builtin.import_tasks: firewall.yml
       when: options.firewall
