options:
  full_installation: "false" # NEED TO CREATE ROLE, DO NOT CHANGE THIS OPTION !!!
  amdgpu: "true" # Set 'amdgpu' to 'false' if you have a Nvidia gpu.
  aur_helper: 
    name: "paru" # Pick your favarite aur helper. 
    binary: "true" 
  hypervisor: "true" # Set 'hypervisor' to 'false' if you don't want to install qemu/virtmanager.
  gamming_packages: "true"
  firewall: "true" # Set 'firewall' to 'false' if you don't want to install ufw.
