user: 
  name: "{{ lookup('env', 'USER') }}"
  shell: "/bin/zsh"
  home: "{{ lookup('env', 'HOME') }}"

amdgpu_packages:
  - mesa
  - lib32-mesa
  - vulkan-radeon
  - lib32-vulkan-radeon
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader
  - libva-mesa-driver
  - lib32-libva-mesa-driver 
  - vulkan-mesa-layers
  - mesa-vdpau
  - lib32-mesa-vdpau

dotfiles:
  url: "https://github.com/DHDcc/MyHyprland.git"
  destination: "{{ user.home }}/.cache/MyHyprland"
  dependencies:
    - rsync
    - git

audio:
  packages:
    - wireplumber
    - pipewire
    - pipewire-pulse
    - flac
    - pavucontrol
  services:
    - pipewire
    - pipewire-pulse
    - wireplumber

hypervisor:
  packages:
    - qemu-full
    - libvirt
    - bridge-utils
    - virt-manager
    - virt-viewer
    - dnsmasq
    - vde2
    - openbsd-netcat
    - ebtables
    - python-lxml
    - iptables
    - libguestfs
  unit: libvirtd.socket
  groups:
    - libvirt
    - kvm
    - libvirt-qemu
    - input
    - disk

fonts:
  pacman:
    - powerline-fonts
    - ttf-linux-libertine
    - ttf-roboto
    - ttf-dejavu
    - cantarell-fonts
    - ttf-bitstream-vera
    - noto-fonts
    - noto-fonts-emoji
    - noto-fonts-extra
    - noto-fonts-cjk
    - ttf-jetbrains-mono-nerd
    - otf-firamono-nerd
    - ttf-iosevka-nerd
  aur:
    - ttf-unifont
  github:
    url: "https://github.com/google/fonts/raw/main/ofl/alfaslabone/AlfaSlabOne-Regular.ttf"
    destination: "{{ user.home }}/.local/share/fonts/AlfaSlabOne.ttf"
    mode: "0644"

themes:
  - nwg-look
  - papirus-icon-theme
  - gnome-themes-extra

dconf:
  key_path: "/org/gnome/desktop/interface"
  value:
    icon_theme: "'Papirus-Dark'"
    font_name: "'Noto Sans 12'"
    gtk_theme: "'Adwaita-dark'"
    color_scheme: "'prefer-dark'"
    cursor_size: "30"

gaming_packages:
  pacman:
    - steam
    - lutris
    - gamemode
    - mangohud
    - wine
  aur: 
    - heroic-games-launcher-bin
    - vesktop-bin

firewall:
  allow_ports:
    - 80
    - 443
    - 53317
  deny_port: 22

hypr_ecosystem:
  pacman:
    - hyprland
    - hyprlock
    - hypridle
    - hyprutils
    - xdg-desktop-portal-hyprland
  aur: 
    - grimblast-git 
    - hyprpicker

essential_packages:
  pacman:
    - firefox
    - udiskie
    - waybar
    - swaync
    - qt5ct
    - qt6ct
    - playerctl
    - gnome-keyring 
    - qt6-wayland
    - qt5-wayland
    - polkit-gnome
    - network-manager-applet
    - swappy 
    - engrampa
    - thunar
    - tumbler
    - gnome-disk-utility
    - thunar-archive-plugin
    - kitty
    - zsh
    - pacman-contrib
    - lsd
    - ranger
    - fzf
    - imv
    - neofetch
    - imagemagick
    - btop
    - p7zip
    - unzip
    - wl-clipboard
    - swww
    - man-db
    - xdg-desktop-portal
    - xdg-desktop-portal-wlr
    - xdg-desktop-portal-gtk
  aur:
    - cava
    - downgrade
    - rofi-lbonn-wayland-git
    - thunar-shares-plugin

extra_packages:
  pacman:
    - yt-dlp
    - ncdu
    - plocate
    - zoxide
    - piper
    - ttyper
    - tldr
    - pika-backup
    - qbittorrent
    - obs-studio
    - zathura
    - zathura-pdf-mupdf
    - bat
    - newsboat
    - tree
  aur:
    - lavat-git
    - onlyoffice-bin
    - localsend-bin
    - feishin-bin
    - freetube-bin
    - spotify
    - vscodium-bin
