user: 
  name: "{{ lookup('env', 'USER') }}"
  shell: "/bin/zsh"
  home: "{{ lookup('env', 'HOME') }}"

amdgpu_packages:
  - lact
  - mesa
  - lib32-mesa
  - vulkan-radeon
  - vulkan-tools
  - rocm-smi-lib
  - lib32-vulkan-radeon
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader
  - vulkan-mesa-layers
  - lib32-mesa-vdpau

dotfiles:
  url: "https://github.com/DHDcc/dotfiles.git"
  destination: "{{ user.home }}/.cache/MyHyprland"
  dependencies:
    - rsync
    - git

audio:
  packages:
    - wireplumber
    - pipewire
    - pipewire-pulse
    - flac
    - pavucontrol
  services:
    - pipewire
    - pipewire-pulse
    - wireplumber

hypervisor:
  packages:
    - qemu-full
    - libvirt
    - bridge-utils
    - virt-manager
    - virt-viewer
    - dnsmasq
    - vde2
    - openbsd-netcat
    - ebtables
    - python-lxml
    - iptables
    - libguestfs
  unit: libvirtd.socket
  groups:
    - libvirt
    - kvm
    - libvirt-qemu
    - input
    - disk

fonts:
  packages:
    - powerline-fonts
    - ttf-linux-libertine
    - ttf-roboto
    - ttf-dejavu
    - cantarell-fonts
    - ttf-bitstream-vera
    - noto-fonts
    - noto-fonts-emoji
    - noto-fonts-extra
    - noto-fonts-cjk
    - ttf-jetbrains-mono-nerd
    - otf-firamono-nerd
    - ttf-iosevka-nerd
    #- ttf-unifont (aur)
  github:
    url: "https://github.com/google/fonts/raw/main/ofl/alfaslabone/AlfaSlabOne-Regular.ttf"
    destination: "{{ user.home }}/.local/share/fonts/AlfaSlabOne.ttf"
    mode: "0644"

themes:
  - nwg-look
  - papirus-icon-theme
  - gnome-themes-extra

dconf:
  key_path: 
    interface: "/org/gnome/desktop/interface"
    button_layout: "/org/gnome/desktop/wm/preferences/button-layout"
  value:
    icon_theme: "'Papirus-Dark'"
    font_name: "'Noto Sans 12'"
    gtk_theme: "'Adwaita-dark'"
    color_scheme: "'prefer-dark'"
    cursor_size: "30"
    cursor_theme: "'Adwaita'"
    button_layout: "':'"

gaming_packages:
  pacman:
    - steam
    - lutris
    - gamemode
    - mangohud
    - lib32-mangohud
    - wine
  aur: 
    - heroic-games-launcher-bin
    - vesktop-bin

firewall:
  allow_ports:
    - 11371
    - 53317
  deny_ports: 
    - 22
    - 80
    - 443

hypr_ecosystem:
  pacman:
    - hyprland
    - hyprlock
    - hypridle
    - hyprutils
    - hyprpicker
    - xdg-desktop-portal-hyprland
  aur: 
    - grimblast-git 

essential:
  packages:
    pacman:
      - uwsm
      - udiskie
      - firefox
      - waybar
      - zoxide
      - rofi-wayland
      - unp
      - swaync
      - qt5ct
      - bat
      - qt6ct
      - playerctl
      - gnome-keyring 
      - qt6-wayland
      - qt5-wayland
      - polkit-gnome
      - network-manager-applet
      - swappy 
      - engrampa
      - thunar
      - tumbler
      - gparted
      - thunar-archive-plugin
      - kitty
      - zsh
      - pacman-contrib
      - lsd
      - yazi
      - fzf
      - imv
      - imagemagick
      - btop
      - unzip
      - wl-clipboard
      - swww
      - man-db
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
    aur:
      - waypaper
      - gpu-screen-recorder-gtk
      - downgrade
      - thunar-shares-plugin
  services:
    - waybar.service
    - swaync.service
    - hypridle.service

extra_packages:
  pacman:
    - cava
    - yt-dlp
    - ncdu
    - plocate
    - piper
    - ttyper
    - tldr
    - pika-backup
    - qbittorrent
    - newsboat
    - tree
  aur:
    - lavat-git
    - onlyoffice-bin
    - localsend-bin
    - feishin-bin
    - freetube-bin
    - vscodium-bin
