user: 
  name: "{{ lookup('env', 'USER') }}"
  directory: "{{ lookup('env', 'HOME') }}"
  uid: "{{ lookup('env', 'UID') }}"

amdgpu_packages:
  - mesa
  - lib32-mesa
  - vulkan-radeon
  - lib32-vulkan-radeon
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader
  - libva-mesa-driver
  - lib32-libva-mesa-driver 
  - vulkan-mesa-layers
  - mesa-vdpau
  - lib32-mesa-vdpau

dotfiles:
  url: "https://github.com/DHDcc/MyHyprland.git"
  destination: "{{ user.directory }}/MyHyprland"

sound:
  packages:
    - wireplumber
    - pipewire
    - pipewire-pulse
    - flac
    - pavucontrol
  services:
    - pipewire
    - pipewire-pulse
    - wireplumber

hypervisor:
  packages:
    - qemu-full
    - libvirt
    - bridge-utils
    - virt-manager
    - virt-viewer
    - dnsmasq
    - vde2
    - openbsd-netcat
    - ebtables
    - python-lxml
    - iptables
    - libguestfs
  service: libvirtd
  groups:
    - libvirt
    - kvm
    - libvirt-qemu
    - input
    - disk

fonts:
  pacman:
    - powerline-fonts
    - ttf-linux-libertine
    - noto-fonts-emoji
    - noto-fonts-extra
  aur:
    - nerd-fonts-git
    - fontpreview-git

themes:
  - nwg-look
  - papirus-icon-theme
  - gnome-themes-extra

gaming_packages:
  pacman:
    - steam
    - lutris
    - gamemode
    - mangohud
    - wine
  aur: heroic-games-launcher-bin

firewall:
  allow_ports:
    - 80
    - 443
    - 53317
  deny_port: 22

terminal_packages:
  pacman:
    - kitty
    - zsh
    - pacman-contrib
    - lsd
    - zoxide
    - ranger
    - zathura
    - fzf
    - imv
    - yt-dlp
    - neofetch
    - ncdu
    - bat
    - imagemagick
    - btop
    - p7zip
    - unzip
    - wl-clipboard
    - newsboat
    - plocate
    - swww
    - tree
    - man-db
    - tldr
    - ttyper
  aur:
    - cava
    - preload
    - lavat-git
    - downgrade

aur_packages:
  - cava
  - downgrade
  - feishin-bin
  - fontpreview-git
  - freetube-bin
  - grimblast-git
  - heroic-games-launcher-bin
  - lavat-git
  #- mullvad-vpn
  - nerd-fonts-git
  - onlyoffice-bin
  - pika-backup
  - preload
  - rofi-lbonn-wayland-git
  - spotify
  - thunar-shares-plugin
  - trilium-bin
  - ventoy-bin
  - vscodium-bin
  - wlogout

hypr_ecosystem:
  pacman:
    - hyprland
    - hyprlock
    - hypridle
    - xdg-desktop-portal-hyprland
  aur: 
    - grimblast-git 
    - hyprpicker

base_packages:
  pacman:
    - firefox
    - pacman-contrib
    - udiskie
    - waybar
    - swaync
    - qt5ct
    - cronie
    - gnome-keyring 
    - qt6-wayland
    - zathura-pdf-mupdf
    - qt5-wayland
    - polkit-gnome
    - network-manager-applet
    - qbittorrent
    - swappy 
    - engrampa
    - obs-studio
    - thunar
    - tumbler
    - gnome-disk-utility
    - thunar-archive-plugin
    - xdg-desktop-portal
    - xdg-desktop-portal-wlr
    - xdg-desktop-portal-gtk
  aur:
   - rofi-lbonn-wayland-git
   - preload
   #- freetube-bin
   - onlyoffice-bin
   - thunar-shares-plugin
   - vscodium-bin
