- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: 0644
    validate: 'visudo -cf %s'

- name: Changing MAKEFLAGS to speed up compilation.
  ansible.builtin.lineinfile:
    path: /etc/makepkg.conf
    search_string: '#MAKEFLAGS='
    line: 'MAKEFLAGS="-j8"'
  become: true

- name: Install "{{ options.aur_helper.name }}" using makepkg
  kewlfft.aur.aur:
    name: "{{ options.aur_helper.name + '-bin' if options.aur_helper.binary == 'true' else options.aur_helper.name }}"
    use: makepkg
    state: present
  become: true
  become_user: aur_builder
