- name: copy pacman.conf
  ansible.builtin.copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: 0644
  become: true
  register: pacman_config

- name: Reload pacman 
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true
  when: pacman_config.changed
