- name: Install xdg-user-dirs.
  community.general.pacman:
    name: xdg-user-dirs
    state: present
  become: true
  register: user_dirs

- name: Setup user directories.
  ansible.builtin.command: /usr/bin/xdg-user-dirs-update
  become: false
  when: user_dirs.changed

- name: Find all directories in the home directory.
  ansible.builtin.find:
    paths: "{{ user.home }}"
    file_type: directory
    recurse: no
  register: found_directories

- name: Rename directories to lowercase.
  ansible.builtin.command: mv "{{ item.path }}" "{{ item.path | dirname }}/{{ item.path | basename | lower }}"
  when: item.path | basename != item.path | basename | lower
  loop: "{{ found_directories.files }}"
  become: false
  changed_when: true
