---

-  name: Archlinux post-installation - Sound 
   hosts: host
   connection: local
   gather_facts: false
   vars_files:
     - ../group_vars/all/vars.yml
   tasks:

     - name: Install pipewire.
       ansible.builtin.pacman:
         name: "{{ sound.packages }}"
         state: present
       become: true

     - name: Enable pipewire services.
       ansible.builtin.systemd_service: 
         name: "{{ item }}"
         enabled: yes
         scope: user
       loop: "{{ sound.services }}"
       become: false


