   - name: Remove conflicting packages
     community.general.pacman:
       name: 
         - iptables
         - iptables-nft
       state: absent
       force: true

   - name: Install qemu/virtmanager
     community.general.pacman:
       name: "{{ hypervisor.packages }}"
       state: present

   - name: Enable/start service
     ansible.builtin.systemd_service:
       name: "{{ hypervisor.service }}"
       state: started
       enabled: yes
   
   - name: Start and autostart default network
     community.libvirt.virt_net:
       name: default
       state: active
       autostart: true

   - name: Add user to the libvirt and kvm group
     ansible.builtin.user:
       name: "{{ user.name }}"
       groups: "{{ hypervisor.groups }}"
       append: yes
     notify: restart libvirtd

   - name: Change firewall backend for libvirt
     ansible.builtin.lineinfile:
       path: "/etc/libvirt/network.conf"
       search_string: "firewall_backend ="
       line: 'firewall_backend = "iptables"'
