- name: Install fonts and themes.
  community.general.pacman:
    name: "{{ fonts.pacman + themes }}"
    state: present
  become: true

- name: Install some fonts with "{{ options.aur_helper.name }}"
  kewlfft.aur.aur:
    use: "{{ options.aur_helper.name }}"
    name: "{{ fonts.aur }}"
    state: present
  become: true
  become_user: aur_builder

- name: Set icons theme.
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus-Dark'"
  become: false

- name: Set text font and size.
  community.general.dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Noto Sans 12'"
  become: false

- name: Set applications theme.
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"
  become: false 

- name: Set color scheme preference to dark.
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
  become: false 

- name: Set cursor size.
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-size"
    value: "30"
  become: false
