---

- name: Archlinux post-installation - Fonts_And_Themes
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all/vars.yml
    - ../group_vars/all/options.yml
  tasks:

    - name: Install fonts and themes.
      community.general.pacman:
        name: "{{ fonts.packages + themes }}"
        state: present
      become: true

    - name: Install fontpreview (aur).
      kewlfft.aur.aur:
        use: "{{ options.aur_helper.name }}"
        name: 
          - fontpreview-git 
          - nsxiv 
        state: present
      become: true
      become_user: "{{ user.name }}"
   
    - name: Create user font directory.
      ansible.builtin.file:
        path: "{{ user.home }}/.local/share/fonts"
        state: directory
        mode: "0755"

    - name: Download AlfaSlabOne font.
      ansible.builtin.get_url:
        url: "{{ fonts.github.url }}"
        dest: "{{ fonts.github.destination }}"
        mode: "{{ fonts.github.mode }}"

    - name: Set icons theme.
      community.general.dconf:
        key: "{{ dconf.key_path }}/icon-theme"
        value: "{{ dconf.value.icon_theme }}"
      become: false

    - name: Set text font and size.
      community.general.dconf:
        key: "{{ dconf.key_path }}/font-name"
        value: "{{ dconf.value.font_name }}"
      become: false

    - name: Set applications theme.
      community.general.dconf:
        key: "{{ dconf.key_path }}/gtk-theme"
        value: "{{ dconf.value.gtk_theme }}"
      become: false 

    - name: Set color scheme preference to dark.
      community.general.dconf:
        key: "{{ dconf.key_path }}/color-scheme"
        value: "{{ dconf.value.color_scheme }}"
      become: false 

    - name: Set cursor size.
      community.general.dconf:
        key: "{{ dconf.key_path }}/cursor-size"
        value: "{{ dconf.value.cursor_size }}"
      become: false

    - name: Set cursor theme.
      community.general.dconf:
        key: "{{ dconf.key_path }}/cursor-theme"
        value: "{{ dconf.value.cursor_theme }}"
      become: false

    - name: copy onetime script.
      ansible.builtin.copy:
        src: "onetime.sh"
        dest: "{{ user.home }}/.scripts"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: '0700'
      become: false

    - name: add onetime script in hyprland config file.
      ansible.builtin.lineinfile:
        dest: "{{ user.home }}/.config/hypr/hyprland.conf"
        line: "exec-once = $HOME/.scripts/onetime.sh"
      become: false
