---

- name: Remove conflicting packages.
  community.general.pacman:
    name: 
      - iptables
      - iptables-nft
    state: absent
    force: true

- name: Install Qemu and Virt-Manager.
  community.general.pacman:
    name: "{{ hypervisor.packages }}"
    state: present

- name: Enable the "{{ hypervisor.unit }}" unit.
  ansible.builtin.systemd:
    name: "{{ hypervisor.unit }}"
    enabled: true
   
- name: Start and autostart default network.
  community.libvirt.virt_net:
    name: default
    state: active
    autostart: true

- name: Add user to libvirt to allow access to VMs.
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "{{ hypervisor.groups }}"
    append: true

- name: Change firewall backend for libvirt.
  ansible.builtin.lineinfile:
    path: "/etc/libvirt/network.conf"
    search_string: "firewall_backend ="
    line: 'firewall_backend = "iptables"'
