---

-  name: Archlinux post-installation - Hypervisor
   hosts: host
   connection: local
   gather_facts: false
   become: true
   vars_files:
     - ../group_vars/all/vars.yml
     - ../group_vars/all/options.yml
   tasks:

     - name: Check if the CPU supports virtualization.
       ansible.builtin.command: "grep -Ec '(vmx|svm)' /proc/cpuinfo"
       register: cpu_virtualization_support
       changed_when: false
       become: false

     - name: Warn if virtualization is not enabled.
       ansible.builtin.debug:
         msg: "Virtualization not enabled in BIOS. Skipping play..."
       when: cpu_virtualization_support.stdout | int == 0
 
     - ansible.builtin.import_tasks: hypervisor.yml
       when: cpu_virtualization_support.stdout | int > 0
