---

-  name: Archlinux post-installation - Dotfiles
   hosts: host
   connection: local
   gather_facts: false
   become: false
   vars_files:
     - ../group_vars/all/vars.yml
   tasks:

     - name: Install dependencies.
       community.general.pacman:
         name: "{{ dotfiles.dependencies }}"
         state: present
       become: true

     - name: Clone dotfiles.
       ansible.builtin.git:
         repo: "{{ dotfiles.url }}"
         dest: "{{ dotfiles.destination }}"
         force: true

     - name: Copy zshenv to "{{ user.home }}".
       ansible.builtin.copy:
         src: "{{ dotfiles.destination }}/.zshenv"
         dest: "{{ user.home }}"
         owner: "{{ user.name }}"
         mode: '0600'
       become: false

     - name: Copy configs directory.
       ansible.posix.synchronize: 
         src: "{{ dotfiles.destination }}/.config/"
         dest:  "{{ user.home }}/.config/"
         recursive: true

     - name: Copy scrpits directory and change permissions.
       ansible.posix.synchronize: 
         src: "{{ dotfiles.destination }}/.scripts"
         dest:  "{{ user.home }}"
         recursive: true
         rsync_opts:
           - "--chmod=700"
