- name: install rsync and git (if not installed)
  community.general.pacman:
    name: 
      - rsync
      - git
    state: present
  become: true

- name: Clone user dotfiles with git
  ansible.builtin.git:
    repo: "{{ dotfiles.url }}"
    dest: "{{ dotfiles.destination }}"
    force: true
  become: false

- name: copy .config directory from dotfiles to home
  ansible.posix.synchronize: 
    src: "{{ dotfiles.destination }}/.config/"
    dest:  "{{ user.directory }}/.config/"
    recursive: true
  become: false

- name: copy .scrpits directory from dotfiles to home and change permissions
  ansible.posix.synchronize: 
    src: "{{ dotfiles.destination }}/.scripts"
    dest:  "{{ user.directory }}"
    recursive: true
    rsync_opts:
      - "--chmod=700"
  become: false

