- name: Install rsync and git.
  community.general.pacman:
    name: 
      - rsync
      - git
    state: present
  become: true

- name: Clone dotfiles with git.
  ansible.builtin.git:
    repo: "{{ dotfiles.url }}"
    dest: "{{ dotfiles.destination }}"
    force: true
  become: false

- name: Copy .config.
  ansible.posix.synchronize: 
    src: "{{ dotfiles.destination }}/.config/"
    dest:  "{{ user.directory }}/.config/"
    recursive: true
  become: false

- name: Copy .scrpits directory and change permissions.
  ansible.posix.synchronize: 
    src: "{{ dotfiles.destination }}/.scripts"
    dest:  "{{ user.directory }}"
    recursive: true
    rsync_opts:
      - "--chmod=700"
  become: false

