- name: Install ly.
  ansible.builtin.pacman: 
    name: ly
    state: present
  become: true

- name: Enable ly service.
  ansible.builtin.systemd_service:
    name: ly
    enabled: yes
  become: true
