---

-  name: Archlinux post-installation - Tweaks
   hosts: host
   connection: local
   gather_facts: false
   become: true
   vars_files:
     - ../group_vars/all/vars.yml
     - ../group_vars/all/options.yml
   tasks:

     - name: Enable trim.
       ansible.builtin.systemd:
         name: fstrim.timer
         enabled: true

     - name: Change swappiness value.
       ansible.builtin.copy:
         dest: "/etc/sysctl.d/99-swappiness.conf"
         content: "vm.swappiness = 10"

     - name: Disable automatic core dumps.
       ansible.builtin.copy:
         dest: "/etc/sysctl.d/50-coredump.conf"
         content: "kernel.core_pattern=|/bin/false"

     - name: Add boot parameters for systemd-boot.
       ansible.builtin.lineinfile:
         path: "/boot/loader/entries/arch.conf"
         regexp: '^(options .*rw)\s*$'
         line: "\\1 loglevel=3 libahci.ignore_sss=1 nowatchdog"
         backrefs: true

     - name: Create pacman hooks directory.
       ansible.builtin.file:
         path: "/etc/pacman.d/hooks"
         state: directory
     
     - name: Add a pacman hook for systemd-boot.
       ansible.builtin.copy:
         src: "95-systemd-boot.hook"
         dest: "/etc/pacman.d/hooks"
         owner: root
         group: root
         mode: 0644

     - name: Install Dash.
       community.general.pacman:
         name: dash
         state: present
       register: install_dash
      
     - name: Use Dash as /bin/sh.
       ansible.builtin.command:
         cmd: /sbin/ln -sfT dash /usr/bin/sh
       when: install_dash.changed

     - name: Add a pacman hook for Bash.
       ansible.builtin.copy:
         src: "bash-update.hook"
         dest: "/etc/pacman.d/hooks"
         owner: root
         group: root
         mode: 0644
       
     - name: Reduce the journal's size.
       ansible.builtin.lineinfile:
         path: "/etc/systemd/journald.conf"
         regexp: '^#SystemMaxUse'
         line: "SystemMaxUse=50M"

     - name: Use the BFQ scheduler.
       ansible.builtin.copy:
         src: "60-ioschedulers.rules"
         dest: "/etc/udev/rules.d/60-ioschedulers.rules"
         owner: root
         group: root
         mode: 0644

     - name: Increase virtual memory.
       ansible.builtin.copy:
         dest: "/etc/sysctl.d/80-virtualmemory.conf"
         content: |
           vm.max_map_count = 2147483642
           vm.min_free_kbytes = 1048576

     - name: Install preload (aur).
       kewlfft.aur.aur:
         name: preload
         use: "{{ options.aur_helper.name }}"
         state: present
       become_user: "{{ user.name }}"
       register: install_preload
       tags: speed_up_app_launch
 
     - name: Enable preload.
       ansible.builtin.systemd:
         name: preload
         enabled: true
       when: install_preload.changed
       tags: speed_up_app_launch

     - name: Install reflector (aur).
       kewlfft.aur.aur:
         name: reflector
         use: "{{ options.aur_helper.name }}"
         state: present
       become_user: "{{ user.name }}"
       register: install_reflector
       tags: mirrorlist

     - name: Backup old mirror list.
       ansible.builtin.copy:
         src: "/etc/pacman.d/mirrorlist"
         dest: "/etc/pacman.d/mirrorlist.back"
       when: install_reflector.changed
       register: backup_mirror     
  
     - name: Fetch the top 10 fastest servers.
       ansible.builtin.command:
         cmd: /sbin/reflector --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
       when: install_reflector.changed and backup_mirror.changed
       register: fastest_servers

     - name: Reload pacman.
       community.general.pacman:
         update_cache: true
       when: fastest_servers.changed
