---

- ansible.builtin.import_playbook: presetup/main.yml

- ansible.builtin.import_playbook: dotfiles/main.yml

- ansible.builtin.import_playbook: system/main.yml

- ansible.builtin.import_playbook: base/main.yml
  when: options.full_installation == false

- ansible.builtin.import_playbook: fonts_and_themes/main.yml

- ansible.builtin.import_playbook: sound/main.yml

- ansible.builtin.import_playbook: hypervisor/main.yml
  when: options.hypervisor

- ansible.builtin.import_playbook: games/main.yml
  when: options.gaming_packages

- ansible.builtin.import_playbook: cleanup/main.yml

