---

- ansible.builtin.import_playbook: user/main.yml

- ansible.builtin.import_playbook: system/main.yml

- ansible.builtin.import_playbook: dotfiles/main.yml

- ansible.builtin.import_playbook: essential/main.yml

- ansible.builtin.import_playbook: fonts_and_themes/main.yml

- ansible.builtin.import_playbook: audio/main.yml

- ansible.builtin.import_playbook: hypervisor/main.yml
  when: options.hypervisor

- ansible.builtin.import_playbook: gaming/main.yml
  when: options.gaming_packages

- ansible.builtin.import_playbook: tweaks/main.yml
  when: options.tweaks

- ansible.builtin.import_playbook: cleanup/main.yml
