---
   
-  name: Archlinux post-installation
   hosts: host
   connection: local
   gather_facts: false
   become: true


   roles:
     - { role: presetup, tags: ['presetup'] }
     - { role: dotfiles, tags: ['dotfiles'] }
     - { role: system, tags: ['system'] }
     - { role: base, tags: ['base'], when: "options.full_installation == 'false'" }
     #- { role: full_install, tags: ['full_install'], when: "options.full_installation == 'true'" }
     - { role: themes, tags: ['themes'] }
     - { role: sound, tags: ['sound'] }
     - { role: hypervisor, tags: ['hypervisor'], when: "options.hypervisor == 'true'" }
     - { role: games, tags: ['games'], when: "options.gamming_packages == 'true'" }
     - { role: cleanup, tags: ['cleanup'] }
  
