---

-  name: Archlinux post-installation - Essential
   hosts: host
   connection: local
   gather_facts: false
   become: true
   vars_files:
     - ../group_vars/all/vars.yml
     - ../group_vars/all/options.yml
   tasks:

     - name: install essential packages.
       community.general.pacman:
         name: "{{ essential_packages.pacman + hypr_ecosystem.pacman }}"
         state: present

     - name: install essential packages (aur).
       kewlfft.aur.aur:
         name: "{{ essential_packages.aur + hypr_ecosystem.aur }}"
         use: "{{ options.aur_helper.name }}"
         state: present
       become_user: "{{ user.name }}"
