- name: install main desktop packages whith pacman
  community.general.pacman:
    name: "{{ base_packages.pacman + hypr_ecosystem.pacman + terminal_packages.pacman + fonts.pacman }}"
    state: present
  become: true

- name: install main desktop packages whith paru
  kewlfft.aur.aur:
    name: "{{ base_packages.aur + hypr_ecosystem.aur + terminal_packages.aur + fonts.aur }}"
    use: paru
    state: present
  become: true
  become_user: aur_builder
