- name: Install xdg-user-dirs
  community.general.pacman:
    name: xdg-user-dirs
    state: present
  become: true
  register: user_dirs

- name: Setup user directorys
  ansible.builtin.command: /usr/bin/xdg-user-dirs-update
  become: false
  when: user_dirs.changed
        

