---

-  name: Archlinux post-installation - Audio
   hosts: host
   connection: local
   gather_facts: false
   vars_files:
     - ../group_vars/all/vars.yml
   tasks:

     - name: Install pipewire.
       ansible.builtin.pacman:
         name: "{{ audio.packages }}"
         state: present
       become: true

     - name: Enable pipewire services.
       ansible.builtin.systemd: 
         name: "{{ item }}"
         enabled: true
         scope: user
       loop: "{{ audio.services }}"
       become: false


