- name: Install gaming packages.
  community.general.pacman:
    name: "{{ gaming_packages.pacman }}"
    state: present
  become: true

- name: Install gaming packages with "{{ options.aur_helper.name }}".
  kewlfft.aur.aur:
    use: "{{ options.aur_helper.name }}"
    name: "{{ gaming_packages.aur }}"
    state: present
  become: true
  become_user: aur_builder
