- name: Install gamming packages whith pacman
  community.general.pacman:
    name: "{{ gamming_packages.pacman }}"
    state: present
  become: true

- name: Install gamming packages with paru
  kewlfft.aur.aur:
    use: "{{ options.aur_helper.name }}"
    name: "{{ gamming_packages.aur }}"
    state: present
  become: true
  become_user: aur_builder
