- name: remove the 'aur_builder' user.
  ansible.builtin.user: 
    name: aur_buider
    state: absent
    remove: yes
  become: true

- name: remove sudoer file of the 'aur_builder' user.
  ansible.builtin.file:
    path: /etc/sudoers.d/11-install-aur_builder
    state: absent
  become: true

